name = "CSyntax"
uuid = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "0.3.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[compat]
CEnum = ">= 0.2.0"
julia = "~1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
